{% set version = "1.6.4" %}

package:
  name: orc
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/orc/orc-{{ version }}/orc-{{ version }}.tar.gz
  sha256: ceea9849277354cffb37853b7f47ea96898c3e716e0803a597ca657cdb59e43c
  patches:
    # ORC builds by default with -Werror but some dependencies omit warnings.
    # This deactivates -Werror
    - 0001-Deactivate-aggressive-failures-on-warnings.patch
    - 0002-Partially-rework-cmake-modules-to-accommodate-librar.patch
    - 0003-Don-t-force-orc-to-be-a-static-library-let-end-user-.patch

build:
  number: 1
  skip: true  # [win]
  # run_exports:
  # https://github.com/lvc/upstream-tracker/issues/88

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja       # [unix]
    # `protoc` is also used for building
    - libprotobuf
    - cmake
  host:
    - zlib
    - snappy
    - libprotobuf
    - lz4-c
    - zstd
  run:
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/lib/liborc${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/orc/Common.hh   # [unix]

about:
  home: http://github.com/apache/orc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ libraries for Apache ORC

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - nehaljwani
